export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_fAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAIL = 'LOGIN_fAIL';

export const LOGOUT = 'LOGOUT';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';


